name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: radekholy24/tyntec-github-action-sms-beta/blob/v1-beta/.github/workflows/build.yml
        with:
          fromPhoneNumber: ${{ secrets.FROM_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.TO_PHONE_NUMBER }}
          message: welcome_message
        env:
          TYNTEC_API_KEY: ${{ secrets.TYNTEC_API_KEY }}
