name: Build
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: radekholy24/tyntec-github-action-sms-beta@v1-beta
        with:
          fromPhoneNumber: ${{ secrets.FROM_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.TO_PHONE_NUMBER }}
          message: welcome_message
        env:
          TYNTEC_API_KEY: ${{ secrets.TYNTEC_API_KEY }}
      - run: |
          echo "Hello world"
